### ISSUE TITLE
Changes omitted from 1.0.4

### ISSUE THREAD

**Issue by jdmarshall** [mortzdk/colorinterpreter#9]
I haven't figured out what's going on. I see commit history that shows that my change is in 1.0.4, but when I pulled down 1.0.4 I see this instead:

{
  "name": "colorinterpreter",
  "version": "1.0.4",
  "description": "ColorInterpreter is a module able to convert any acceptable browser color-scheme to any other acceptable browser color-scheme.",
...
  "main": "index.js",
  "dependencies": {
    "jsdoc": "^3.4.3",
    "jsdoc-to-markdown": "^3.0.0",
    "uglify-js": "^2.8.22",
    "minami": "1.1.1"
  },

Something with the build pipeline perhaps?

**Comment by jdmarshall** [comment]
@mortzdk Any idea here?  I was trying to figure out if I could file a PR to bump the version but I don't think I understand the library structure well enough for that.

**Comment by mortzdk** [comment]
Should be solved with version 1.0.5
